Document: meetaccountmanager
Title: Debian meetaccountmanager Manual
Author: <insert document author here>
Abstract: This manual describes what meetaccountmanager is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/meetaccountmanager/meetaccountmanager.sgml.gz

Format: postscript
Files: /usr/share/doc/meetaccountmanager/meetaccountmanager.ps.gz

Format: text
Files: /usr/share/doc/meetaccountmanager/meetaccountmanager.text.gz

Format: HTML
Index: /usr/share/doc/meetaccountmanager/html/index.html
Files: /usr/share/doc/meetaccountmanager/html/*.html
